package wang.switchy.hin2n.storage.db.base;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import wang.switchy.hin2n.storage.db.base.model.N2NSettingModel;
import wang.switchy.hin2n.storage.db.base.model.ZerotierSettingModel;

import wang.switchy.hin2n.storage.db.base.N2NSettingModelDao;
import wang.switchy.hin2n.storage.db.base.ZerotierSettingModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig n2NSettingModelDaoConfig;
    private final DaoConfig zerotierSettingModelDaoConfig;

    private final N2NSettingModelDao n2NSettingModelDao;
    private final ZerotierSettingModelDao zerotierSettingModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        n2NSettingModelDaoConfig = daoConfigMap.get(N2NSettingModelDao.class).clone();
        n2NSettingModelDaoConfig.initIdentityScope(type);

        zerotierSettingModelDaoConfig = daoConfigMap.get(ZerotierSettingModelDao.class).clone();
        zerotierSettingModelDaoConfig.initIdentityScope(type);

        n2NSettingModelDao = new N2NSettingModelDao(n2NSettingModelDaoConfig, this);
        zerotierSettingModelDao = new ZerotierSettingModelDao(zerotierSettingModelDaoConfig, this);

        registerDao(N2NSettingModel.class, n2NSettingModelDao);
        registerDao(ZerotierSettingModel.class, zerotierSettingModelDao);
    }
    
    public void clear() {
        n2NSettingModelDaoConfig.clearIdentityScope();
        zerotierSettingModelDaoConfig.clearIdentityScope();
    }

    public N2NSettingModelDao getN2NSettingModelDao() {
        return n2NSettingModelDao;
    }

    public ZerotierSettingModelDao getZerotierSettingModelDao() {
        return zerotierSettingModelDao;
    }

}
